#tomcat-app
namespace: tomcat-sample

image:
  repository: 192.168.1.37:5000/tomcat-sample
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8181

service:
  name: tomcat
  type: NodePort
  port: 8181
  nodePort: 30080

imagePullSecrets:
  - name: image-registry-secret

livenessProbe:
  httpGet:
    path: /
    port: 8181
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8181
  initialDelaySeconds: 15
  periodSeconds: 5

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
